name: prova_login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  cookie_jar: ^3.0.1
  device_info_plus: ^8.2.2
  dio: ^5.1.2
  dio_cookie_manager: ^2.1.3
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.6

  flutter_signin_button: ^2.0.0
  flutter_spinkit: ^5.2.0
  http: ^0.13.5
  icalendar_parser: ^1.1.1
  intl: ^0.18.0
  line_awesome_flutter: ^2.0.0
  path_provider: ^2.0.14
  permission_handler: ^10.2.0
  provider: ^6.0.0
  syncfusion_flutter_datepicker: ^19.2.57
  share_plus: ^6.3.2
  table_calendar: ^3.0.9
  url_launcher: ^6.0.17
  google_maps_flutter_web: ^0.4.0+8
  search_map_place_updated: ^0.0.4


  webview_flutter: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/
  