name: prova_login
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  http: ^0.13.4
  shared_preferences: ^2.0.12
  flutter:
    sdk: flutter

  provider: ^6.0.0
  dio_cookie_manager: ^2.1.3
  cookie_jar: ^3.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true



  